export enum Rank {
    "Not Verified",
    "Deputy US Marshal I",
    "Deputy US Marshal II",
    "Deputy US Marshal III",
    "Deputy US Marshal IV",
    "Deputy US Marshal V",
    "Super Deputy US Marshal",
    "Detective US Marshal",
    "Sergeant",
    "Staff Sergeant",
    "Drill Sergeant",
    "Commander",
    "Lieutenant",
    "Lieutenant Commander",
    "Safety US Marshal",
    "Deputy Chief",
    "Assistant Chief of US Marshals",
    "Chief of US Marshals",
}
